### ISSUE TITLE
Docker hub image at version 0.7.0, tag new release?

### ISSUE THREAD

**Issue by ctcherry** [honeycombio/samproxy#106]
I was looking at the docker hub available image and I see it is a bit old. Would you recommending using the 0.7.0 image that is on docker hub?

Changes since last release:
https://github.com/honeycombio/samproxy/compare/ba8a5b766765e6f4f0a14dfd8da930a5faac0c4b...main

If using version 0.7.0 is not recommended, would it be possible to tag a more recent commit as a release so docker hub is updated?

**Comment by martin308** [comment]
I would hold out for the 0.8.0 release that we are planning on putting out in the near term, there should be 0.8.0-rc1 up on docker hub but the release process broke for that one. The next one will be published automatically 🤞

**Comment by ctcherry** [comment]
Thanks!
