### ISSUE TITLE
Remove traces from cache when sent

### ISSUE THREAD

**Issue by dcarley** [honeycombio/samproxy#116]
We have a theory that the memory problems that we're seeing in #94 may be a result of larger traces (by quantity and size of spans) being cached for longer during our low traffic periods. It occurred to us that traces (and their spans) aren't currently removed from the cache and eligible for GC until their position in the ring buffer is used again, regardless of whether the trace has already been sent.

Could traces be removed from the cache at the time of sending? Or, if the concurrent access is likely to cause race conditions, maybe zero out the references to spans, as they aren't size bound by the `CacheCapacity`?

**Comment by martin308** [comment]
@dcarley thanks for bringing this up! I've added it to our backlog for our current period of work on samproxy so that we can prioritize accordingly

**Comment by ianwilkes** [comment]
Done in v0.10.0
