### ISSUE TITLE
Cache capacity and usage metrics

### ISSUE THREAD

**Issue by dcarley** [honeycombio/samproxy#117]
It'd be great to have some better metrics about how the cache is being used, both to use when [sizing the cache](https://honeycombpollinators.slack.com/archives/CG8M2GY3U/p1595602070080400) and [investigating memory usage](https://github.com/honeycombio/samproxy/issues/94). We'd particularly like to know how many traces in the cache are sent/free vs unsent/used and how many spans they contain. This might only be possible by periodically iterating through the cache - would you foresee this causing any performance problems?

**Comment by martin308** [comment]
@dcarley thanks for bringing this up! I've added it to our backlog for our current period of work on samproxy so that we can prioritize accordingly
