### ISSUE TITLE
Docker Hub image publishing

### ISSUE THREAD

**Issue by dcarley** [honeycombio/samproxy#60]
Are the images published to Docker Hub "supported" for public consumption?

- https://hub.docker.com/r/honeycombio/samproxy/tags

Are they built and pushed manually at the moment? If so, could they be automated by CI, at the same time as creating a GitHub release, so that they remain consistent?

**Comment by tredman** [comment]
Yes, they are supported. Getting publishing automated is on my shortlist of things to do once development picks up again. :)

**Comment by dcarley** [comment]
Perfect, thanks! (I'd raise a PR myself but credentials)

**Comment by dcarley** [comment]
I also noticed while doing some testing that the latest release binary was built with Go 1.10.8 and the latest Docker image was built with Go 1.9.4. I imagine there are some runtime improvements (like GC) to be had from building with later Go versions.

**Comment by martin308** [comment]
@dcarley hopefully once #67 has been merged we should be publishing to docker hub on tagged builds. We've also updated to go 1.14 compilation as of #64
