### ISSUE TITLE
Trace timeout metric

### ISSUE THREAD

**Issue by c2nes** [honeycombio/samproxy#72]
I would like to suggest adding a counter metric that is incremented when `TraceTimeout` is hit.

We are trying to tune `SendDelay` to avoid spans arriving after the trace has already been flushed from the Samproxy instance. We know that we have at least some spans arriving late because we see `trace_sent_cache_hit` being incremented. What we don't know is how often spans arrive after the trace has been evicted from the sent trace cache.

We know in this case that the span will be treated by Samproxy as a new trace. We also know that the root span for the trace has already come and gone, so the "new" trace will only be flushed when `TraceTimeout` is hit. If Samproxy provided a trace timeout metric then we'd have a proxy metric for late arriving spans.

Note, this metric would also be valuable for us in setting `CacheCapacity` as we don't know what portion of the cache is currently going towards caching these late arriving spans.

**Comment by ianwilkes** [comment]
@c2nes the next release will include two counters: `trace_send_has_root` and `trace_send_no_root`, to trace spans which do and don't have root spans at the time they're sent. This isn't quite what you asked for, but should serve the same purpose.
