### ISSUE TITLE
cannot find package "github.com/vmihailenco/msgpack/v4"

### ISSUE THREAD

**Issue by sineo** [honeycombio/samproxy#95]
My docker build fails because it cannot find package "github.com/vmihailenco/msgpack/v4". Have you experienced this issue? Any advice on how to resolve it?
 
```
docker build -t samproxy .
Sending build context to Docker daemon  9.204MB
Step 1/6 : FROM golang:alpine
alpine: Pulling from library/golang
df20fa9351a1: Already exists 
ed8968b2872e: Pull complete 
a92cc7c5fd73: Pull complete 
00abe362642d: Pull complete 
e0491c15e88f: Pull complete 
Digest: sha256:d6deb50437547fd7226890aa19b075fbf7f5063e3c0d7a2eaf7fb41d11069013
Status: Downloaded newer image for golang:alpine
 ---> 30df784d6206
Step 2/6 : RUN apk add --update --no-cache git
 ---> Running in 74496b0f0285
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
(1/5) Installing nghttp2-libs (1.41.0-r0)
(2/5) Installing libcurl (7.69.1-r0)
(3/5) Installing expat (2.2.9-r1)
(4/5) Installing pcre2 (10.35-r0)
(5/5) Installing git (2.26.2-r0)
Executing busybox-1.31.1-r16.trigger
OK: 22 MiB in 20 packages
Removing intermediate container 74496b0f0285
 ---> 4e7c00c4eeb8
Step 3/6 : RUN go get github.com/honeycombio/samproxy/cmd/samproxy
 ---> Running in 7dc3b072ccf1
package github.com/vmihailenco/msgpack/v4: cannot find package "github.com/vmihailenco/msgpack/v4" in any of:
        /usr/local/go/src/github.com/vmihailenco/msgpack/v4 (from $GOROOT)
        /go/src/github.com/vmihailenco/msgpack/v4 (from $GOPATH)
The command '/bin/sh -c go get github.com/honeycombio/samproxy/cmd/samproxy' returned a non-zero code: 1

**Comment by lizthegrey** [comment]
Same issue as https://github.com/honeycombio/libhoney-go/issues/77

**Comment by sineo** [comment]
Thanks. I'll close this out as duplicate.

**Comment by lizthegrey** [comment]
No, please do keep this open to track fixing it downstream here.

Can you confirm which version of Go you're using, and whether you're using Go Modules?

**Comment by sineo** [comment]
I'm using the Dockerfile in the repo. It's using the `golang:alpine` container which is running go version go1.14.6 linux/amd64.

**Comment by lizthegrey** [comment]
I see the problem, `github.com/vmihailenco/msgpack v4.0.4+incompatible // indirect` is in go.mod but the dependent packages have changed and libhoney now uses `github.com/vmihailenco/msgpack/v4` but go.mod/go.sum here haven't been updated. I'll put out a PR.

**Comment by martin308** [comment]
@lizthegrey see #96 this fixes it

**Comment by lizthegrey** [comment]
sounds good. we should still update the msgpack dependency to move past v4.0.4-incompatible tho

**Comment by lizthegrey** [comment]
#96 is merged, closing this issue. I'll do the followup to update msgpack dep
